version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_container'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "8080:15672"
      - "15672:15672"
    expose:
      - 5672
    networks: 
      - ebeautysalon_network
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 10s
        retries: 5

  ebeautysalon_sql:
    container_name: ebeautysalon_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - ${SQL_PORT}:1433
    expose:
      - 1433
    networks:
      - ebeautysalon_network

  ebeautysalon_api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=${SQL_HOST},1433;Database=${SQL_DATABASE};User=${SQL_USER};Password=${SQL_PASSWORD};ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    ports:
      - "5145:5145"
    networks:
      - ebeautysalon_network
    links:
      - ebeautysalon_sql
    depends_on:
      - ebeautysalon_sql
      - rabbitMQ

  rabbitmq-consumer:
    restart: unless-stopped
    build:
      context: ./eBeautySalon.Subscriber
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
       rabbitMQ:
          condition: service_healthy

    networks:
      - ebeautysalon_network

volumes:
  rabbitmq_data:

networks:
  ebeautysalon_network:
    driver: bridge
  NETWORK:
    external: true
