version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_container'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "8080:15672"
      - "15672:15672"
    expose:
      - 5672
    networks: 
      - ebeautysalon_network
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 10s
        retries: 5

  ebeautysalon_sql:
    container_name: ebeautysalon_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mySqlP4ssword!
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - ebeautysalon_network

  ebeautysalon_api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ebeautysalon_sql,1433;Database=IB200070;User=sa;Password=mySqlP4ssword!;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5145:5145"
    networks:
      - ebeautysalon_network
    links:
      - ebeautysalon_sql
    depends_on:
      - ebeautysalon_sql
      - rabbitMQ

  rabbitmq-consumer:
    restart: unless-stopped
    build:
      context: ./eBeautySalon.Subscriber
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=servicebeautysalon@gmail.com
      - SMTP_PASSWORD=dueyooomounilqqa
    depends_on:
      # - ebeautysalon_sql
      # - ebeatysalon_api
      # - rabbitMQ
       rabbitMQ:
          condition: service_healthy

    networks:
      - ebeautysalon_network

volumes:
  rabbitmq_data:

networks:
  ebeautysalon_network:
    driver: bridge
  NETWORK:
    external: true
